# enable Windows Remote Desktop without password
# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  matrix:
    - PYTHON: "C:\\Python35"
      TOXENV: "py35"
    - PYTHON: "C:\\Python27"
      TOXENV: "py27"

cache:
    - '%LOCALAPPDATA%\pip\Cache'

version: '{branch}.{build}'

install:
  - "%PYTHON%\\python.exe -m pip install tox"

build: off

test_script:
  - "%PYTHON%\\Scripts\\tox.exe"
